# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wi3kOM3vgCKd1uxj1n5HyEspXQKnDmwW
"""

import numpy as np


class NumpyAnalyzer:

    # Constructor
    def __init__(self):
        self.arr = None

    # Static method
    @staticmethod
    def title():
        print("\n==============================")
        print("       NUMPY ANALYZER")
        print("==============================")

    # Class method
    @classmethod
    def create_empty(cls):
        obj = cls()
        obj.arr = np.array([])
        return obj

    # Create array
    def create_array(self):

        print("\n1. 1D Array")
        print("2. 2D Array")
        print("3. 3D Array")

        choice = int(input("Enter choice: "))

        if choice == 1:

            data = input("Enter numbers: ")
            data = list(map(int, data.split()))

            self.arr = np.array(data)

        elif choice == 2:

            rows = int(input("Enter rows: "))
            cols = int(input("Enter columns: "))

            data = input("Enter numbers: ")
            data = list(map(int, data.split()))

            self.arr = np.array(data).reshape(rows, cols)

        elif choice == 3:

            layers = int(input("Enter layers: "))
            rows = int(input("Enter rows: "))
            cols = int(input("Enter columns: "))

            data = input("Enter numbers: ")
            data = list(map(int, data.split()))

            self.arr = np.array(data).reshape(layers, rows, cols)

        else:
            print("Wrong choice")
            return

        print("\nYour Array:")
        print(self.arr)

    # Private method - encapsulation
    def __array_info(self):

        print("\nArray Information")
        print("Shape:", self.arr.shape)
        print("Dimensions:", self.arr.ndim)

    # Indexing and slicing
    def indexing_slicing(self):

        if self.arr is None:
            print("Create an array first.")
            return

        self.__array_info()

        print("\nIndexing and Slicing")

        if self.arr.ndim == 1:

            print("First element:", self.arr[0])
            print("First 3 elements:", self.arr[:3])

        elif self.arr.ndim == 2:

            print("First element:", self.arr[0, 0])
            print("First row:", self.arr[0])
            print("First column:", self.arr[:, 0])
            print("First two rows:")
            print(self.arr[:2])

        elif self.arr.ndim == 3:

            print("First element:", self.arr[0, 0, 0])
            print("First layer:")
            print(self.arr[0])

            print("First row of first layer:")
            print(self.arr[0, 0])

    # Mathematical operations
    def mathematical_operations(self):

        if self.arr is None:
            print("Create an array first.")
            return

        print("\n1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        print("5. Dot Product")
        print("6. Matrix Multiplication")

        choice = int(input("Enter choice: "))

        data = input("Enter second array: ")
        data = list(map(int, data.split()))

        if choice == 6:

            rows = int(input("Enter rows of second matrix: "))
            cols = int(input("Enter columns of second matrix: "))

            arr2 = np.array(data).reshape(rows, cols)

        else:

            arr2 = np.array(data).reshape(self.arr.shape)

        if choice == 1:
            print("\nAddition:")
            print(self.arr + arr2)

        elif choice == 2:
            print("\nSubtraction:")
            print(self.arr - arr2)

        elif choice == 3:
            print("\nMultiplication:")
            print(self.arr * arr2)

        elif choice == 4:
            print("\nDivision:")
            print(self.arr / arr2)

        elif choice == 5:
            print("\nDot Product:")
            print(np.dot(self.arr, arr2))

        elif choice == 6:
            print("\nMatrix Multiplication:")
            print(np.matmul(self.arr, arr2))

        else:
            print("Wrong choice")

    # Combine and split
    def combine_split(self):

        if self.arr is None:
            print("Create an array first.")
            return

        print("\n1. Combine Arrays")
        print("2. Split Array")

        choice = int(input("Enter choice: "))

        if choice == 1:

            data = input("Enter second array: ")
            data = list(map(int, data.split()))

            arr2 = np.array(data)

            combined = np.concatenate((self.arr.flatten(),
                                       arr2.flatten()))

            print("\nCombined Array:")
            print(combined)

        elif choice == 2:

            parts = int(input("How many parts? "))

            result = np.array_split(self.arr, parts)

            print("\nSplit Arrays:")

            for i in range(len(result)):
                print("Part", i + 1)
                print(result[i])

        else:
            print("Wrong choice")

    # Search, sort and filter
    def search_sort_filter(self):

     if self.arr is None:
        print("Please create an array first.")
        return

     print("\nCurrent Array:")
     print(self.arr)

     print("\n1. Search")
     print("2. Sort Ascending")
     print("3. Sort Descending")
     print("4. Filter")

     choice = int(input("Enter choice: "))

    # Search
     if choice == 1:

        number = int(input("Enter number to search: "))

        positions = np.where(self.arr == number)

        if len(positions[0]) == 0:
            print("Number not found.")

        else:
            print("Number found at:")
            print(positions)

    # Ascending
     elif choice == 2:

        result = np.sort(self.arr.flatten())

        print("\nAscending order:")
        print(result)

    # Descending
     elif choice == 3:

        result = np.sort(self.arr.flatten())

        result = result[::-1]

        print("\nDescending order:")
        print(result)

    # Filter
     elif choice == 4:

        number = int(input("Enter value: "))

        result = self.arr[self.arr > number]

        print("\nValues greater than", number, ":")
        print(result)

     else:
        print("Invalid choice.")

    # Aggregate functions
    def aggregates(self):

        if self.arr is None:
            print("Create an array first.")
            return

        print("\nSum:", np.sum(self.arr))
        print("Mean:", np.mean(self.arr))
        print("Median:", np.median(self.arr))
        print("Standard Deviation:", np.std(self.arr))
        print("Variance:", np.var(self.arr))

    # Statistical functions
    def statistics(self):

        if self.arr is None:
            print("Create an array first.")
            return

        print("\nMinimum:", np.min(self.arr))
        print("Maximum:", np.max(self.arr))

        p = float(input("Enter percentile: "))

        print("Percentile:", np.percentile(self.arr, p))

        print("\nCorrelation")

        data = input("Enter another 1D array: ")
        data = list(map(int, data.split()))

        arr2 = np.array(data)

        if self.arr.ndim == 1 and len(self.arr) == len(arr2):

            print("Correlation:",
                  np.corrcoef(self.arr, arr2)[0, 1])

        else:

            print("Correlation needs two 1D arrays of same size.")


# Main program

obj = NumpyAnalyzer()

while True:

    NumpyAnalyzer.title()

    print("\n1. Create Array")
    print("2. Indexing and Slicing")
    print("3. Mathematical Operations")
    print("4. Combine or Split Arrays")
    print("5. Search, Sort and Filter")
    print("6. Aggregate Functions")
    print("7. Statistical Functions")
    print("8. Exit")

    choice = int(input("\nEnter your choice: "))

    if choice == 1:
        obj.create_array()

    elif choice == 2:
        obj.indexing_slicing()

    elif choice == 3:
        obj.mathematical_operations()

    elif choice == 4:
        obj.combine_split()

    elif choice == 5:
        obj.search_sort_filter()

    elif choice == 6:
        obj.aggregates()

    elif choice == 7:
        obj.statistics()

    elif choice == 8:
        print("\nThank you for using NumPy Analyzer!")
        break

    else:
        print("\nWrong choice. Try again.")